apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - name: active
    port: 21
    targetPort: 21
  - name: passive
    port: 30000
    targetPort: 30000
